version = 0.1
[default.deploy.parameters]
stack_name = "LNWeb-API"
resolve_s3 = true
s3_prefix = "LNWeb-API"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
