version = 0.1
[default.deploy.parameters]
stack_name = "lnwebapi-lambda-layer"
resolve_s3 = true
s3_prefix = "lnwebapi-lambda-layer"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
